### ISSUE TITLE
Can't connect to plex after upgrade the adapter to 0.8.9

### ISSUE THREAD

**Issue by vistalba** [Zefau/ioBroker.plex#23]
updated adapter to 0.8.9 and added a token for access.
Adapter can't access my plex server anymore.

Plex Server is running on a remote machine witch is reachable over DNS Name and a proper Let's Encrypt Certificate on Port 443.

I think that is the problem, why the Adapter is unable to connect anymore. Before the update it was running without problems.

**Comment by Zefau** [comment]
Could you change your instance to `debug` (via Instances -> Expert Mode -> Dropdown to `debug`) and provide the log of the failed connection?

**Comment by vistalba** [comment]
@Zefau 

Sure... did it and tried with both "SSL" and without. I'm not sure about the settings with SSL. Why should I select a certificate? The Certificate is presented by the plex server and is a valid Let's encrypt cert so it should be trusted anyway?!

```
2019-12-17 08:34:42.879 - info: plex.0 (4474) Got terminate signal TERMINATE_YOURSELF
2019-12-17 08:34:42.881 - info: plex.0 (4474) Adapter stopped und unloaded.
2019-12-17 08:34:42.882 - info: plex.0 (4474) terminating
2019-12-17 08:34:42.883 - info: plex.0 (4474) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
2019-12-17 08:34:47.330 - debug: plex.0 (5111) Redis Objects: Use Redis connection: 127.0.0.1:9001
2019-12-17 08:34:47.365 - debug: plex.0 (5111) Objects client ready ... initialize now
2019-12-17 08:34:47.369 - debug: plex.0 (5111) Objects create PubSub Client
2019-12-17 08:34:47.370 - debug: plex.0 (5111) Objects client initialize lua scripts
2019-12-17 08:34:47.383 - debug: plex.0 (5111) objectDB connected
2019-12-17 08:34:47.386 - debug: plex.0 (5111) Redis States: Use Redis connection: 127.0.0.1:9000
2019-12-17 08:34:47.388 - debug: plex.0 (5111) Objects connected to redis: 127.0.0.1:9001
2019-12-17 08:34:47.396 - debug: plex.0 (5111) States create PubSub Client
2019-12-17 08:34:47.397 - debug: plex.0 (5111) statesDB connected
2019-12-17 08:34:47.450 - debug: plex.0 (5111) States connected to redis: 127.0.0.1:9000
2019-12-17 08:34:48.281 - info: plex.0 (5111) starting. Version 0.8.9 in /opt/iobroker/node_modules/iobroker.plex, node: v10.17.0
2019-12-17 08:34:48.314 - info: plex.0 (5111) Establishing insecure connection to Plex Media Server...
2019-12-17 08:34:48.407 - debug: plex.0 (5111) Error: socket hang up
at createHangUpError (_http_client.js:323:15)
at Socket.socketOnEnd (_http_client.js:426:23)
at Socket.emit (events.js:203:15)
at endReadableNT (_stream_readable.js:1143:12)
at process._tickCallback (internal/process/next_tick.js:63:19)
2019-12-17 08:34:48.408 - warn: plex.0 (5111) socket hang up
```

**Comment by Zefau** [comment]
Wondering why you have problems connecting even with ssl / https off.

Do you have the chance to change the local adapter file?
If so, please remove the following line and try again (restart adapter):

https://github.com/Zefau/ioBroker.plex/blob/55c102e88b27cb7f3d445971ded966767dc114e2/plex.js#L150

Alternatively I can setup a fork with the change.

**Comment by vistalba** [comment]
> Wondering why you have problems connecting even with ssl / https off.
> 
> Do you have the chance to change the local adapter file?
> If so, please remove the following line and try again (restart adapter):
> 
> https://github.com/Zefau/ioBroker.plex/blob/55c102e88b27cb7f3d445971ded966767dc114e2/plex.js#L150
> 
> Alternatively I can setup a fork with the change.

I removed the line 150 fomr plex.js file but it doesn't connect.

My server does only allow HTTPS. There is no HTTP. If you try to connect with HTTP you will be redirected to HTTPS.

**Comment by Zefau** [comment]
Could you install v0.8.10 from Github? This adds more details to the log. Could you please copy the extended log in here? Thanks!

**Comment by Zefau** [comment]
@vistalba

**Comment by vistalba** [comment]
@Zefau I moved away from ioBroker because I run into multiple issues with GUI, Plex and other plugins too.
